### ISSUE TITLE
History problems between shared song and owned song

### ISSUE THREAD

**Issue by Tembrel** [jsrmath/markato#23]
Two ways to get from a shared song page back to one's own songs:
1. Click on the `here` link in the `alert-warning` paragraph.
2. Choose a song from the `Select Song` dropdown.

There are problems with both.

In the first instance, [the link is to `#`](https://github.com/jsrmath/markato/blob/ae10403450f462d323857f4099c37caea7f75dea/public/scripts/MarkatoPage.cjsx#L167) and the logic to leave the shared song mode is in [the onclick handler](https://github.com/jsrmath/markato/blob/ae10403450f462d323857f4099c37caea7f75dea/public/scripts/MarkatoPage.cjsx#L156-L159). This handler does not stop event propagation, so it gets both the `@removeSharedSong` behavior, which pushes the hash-free state (`https://markato.studio`), and the normal `<a href="#"...>...</a>` behavior, which pushes the blank hash state (`https://markato.studio/#`). On Chrome/Win8.1, at least, this means two back button presses to get back to the shared song URL, but the screen doesn't refresh to show the shared song.

In the second case, only the `@removeSharedSong` handler is called, so only the hash-free state is pushed, and it takes only one back button press to get back to the shared song URL, but the screen still doesn't refresh to show the shared song.

**Comment by jsrmath** [comment]
Well spotted.  This was a case of me implementing song sharing somewhat hastily and not really thinking about all the implications.  The behavior for the two should definitely be the same.  In terms of what that behavior should be, I'm leaning toward redirecting to `/` with JavaScript so that history functions properly.  The only downside is that you have to wait for the page to reload, but I don't think that's a big deal.
